package Labs;

/*
1.Jordan Penaloza
2. 6/25/2022
3. This program allows the user to play a guessing game given a max and min value and
displays the amount of guesses it took to answer correctly.
4. I give myself a 100% because I met every requirement in the rubric to get a 100%.
 */
import java.util.*;

public class GuessPenaloza {

	public static final int MIN = 500;
	public static final int MAX = 600;

	public static void main(String[] args) {
		Scanner console = new Scanner(System.in);
		giveIntro();
		run(console);
	}
	/*Creates a random number to use in the guessing game and prompts the user if they
     want to play again */
	public static void run(Scanner console)
	{  
		Random r = new Random ();
		String choice = "yes";
		while (choice == "yes") {
			int rng = r.nextInt(MIN,MAX);      
			int gameValue = playGame(console, rng); 
			System.out.println("You guessed correctly and it took you " + gameValue + " guesses!");
			System.out.println("Would you like to play again? yes/no");
			choice = console.next();     
		}
	}




	/*Displays the intro on how to play the game*/
	public static void giveIntro() {
		System.out.println("Hi my name is puter");
		System.out.println("I want to play a guessing game with you");
		System.out.println("I'm thinking of a number between 500 and 600");
		System.out.println("I will allow you to guess until you guess correctly");
		System.out.println("After every guess I will tell you if the right answer is higher or lower tn your guess");



	}
	/*Plays the guessing game and ups the count of guesses based on how many guesses the user makes
      as well as prompts the user to guess and tells the user if the guess was lower or higher than the correct guess*/
	public static int playGame(Scanner console, int num) {// variable num holds the random number generated by the computer
		int count = 0;
		int guess = 0;
		System.out.println("Enter a number between " + MIN + " and " + MAX);
		while (guess != num) { 
			System.out.println("What is your guess?"); 
			guess = console.nextInt();
			if (guess < num) {
				System.out.println("Your guess was lower than the correct answer, try again."); 
			} else if (guess > num) {
				System.out.println("Your guess was larger than the correct answer, try again");
			}
			count++;
		}
		return count; 
	}

}
